# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a smaller node image for the runtime
FROM node:18-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy the build output and other necessary files from the builder stage
COPY --from=builder /app/build /app/build
COPY package.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Copy the .env file
COPY .env ./

# Define the environment variables
ENV NODE_ENV=production

# Expose the necessary port (if known)
EXPOSE 3000

# Run the server
CMD ["node", "build/index.js"]